export const LOAD_DRAMAS = 'LOAD_DRAMAS'
export const LOAD_DRAMAS_SUCCESS = 'LOAD_DRAMAS_SUCCESS'
export const LOAD_DRAMAS_ERROR = 'LOAD_DRAMAS_ERROR'

export const LOAD_DRAMA = 'LOAD_DRAMA'
export const LOAD_DRAMA_SUCCESS = 'LOAD_DRAMA_SUCCESS'
export const LOAD_DRAMA_ERROR = 'LOAD_DRAMA_ERROR'
